product:
    name: Java Reference
    sku: 293083
spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/schedule?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: